# Generated by Django 5.0.4 on 2024-05-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidcodercarnivalapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
