# Generated by Django 5.0.4 on 2024-04-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidcodercarnivalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
