# Generated by Django 5.0.4 on 2024-04-28 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidcodercarnivalapi', '0004_alter_challenge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='challenges',
            field=models.ManyToManyField(related_name='competitions', to='kidcodercarnivalapi.challenge'),
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
