# Generated by Django 5.0.4 on 2024-04-29 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidcodercarnivalapi', '0005_competition_challenges_competition_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='challenges',
            field=models.ManyToManyField(related_name='challenges', to='kidcodercarnivalapi.challenge'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
