# Generated by Django 5.0.4 on 2024-04-29 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidcodercarnivalapi', '0008_alter_competition_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participants', to='kidcodercarnivalapi.competition'),
        ),
    ]
